name: deploy-api

on:
  push:
    branches: [master]
    paths:
      - "apps/api/**"
  pull_request:
    branches: [master]
    paths:
      - "apps/api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          yarn install

      - name: Build application
        run: |
          yarn run api:build

      - name: Prune development dependencies
        run: |
          npm prune --production
      
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          cd apps/api && flyctl deploy --remote-only --config apps/api/fly.toml || { echo 'Deployment failed'; exit 1; }
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}